<a href="https://colab.research.google.com/github/kyik1/Math-200/blob/main/Mean_Median_Mode_Lab_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You will learn all about how to use Python to create Summary Statistics

*  mean()
*  median()
mode()
groupby

In [31]:
import pandas as pd

In [32]:
link = 'https://raw.githubusercontent.com/kmath22/kmath22/main/Data%20Science%20Jobs%20Salaries.csv'

ds_df = pd.read_csv(link)
ds_df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021e,EN,FT,Data Science Consultant,54000,EUR,64369,DE,50,DE,L
1,2020,SE,FT,Data Scientist,60000,EUR,68428,GR,100,US,L
2,2021e,EX,FT,Head of Data Science,85000,USD,85000,RU,0,RU,M
3,2021e,EX,FT,Head of Data,230000,USD,230000,RU,50,RU,L
4,2021e,EN,FT,Machine Learning Engineer,125000,USD,125000,US,100,US,S
...,...,...,...,...,...,...,...,...,...,...,...
240,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
241,2021e,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
242,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
243,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
244,2021e,SE,FT,Data Science Manager,7000000,INR,94917,IN,50,IN,L

In [33]:
#What is the average salary of a data scientist?
ds_df['salary_in_usd'].mean().round()

99868.0

In [34]:
#What is the median salary of a data scientist?
ds_df['salary_in_usd'].median()

81000.0

In [35]:
#What is the mode?
ds_df['salary_in_usd'].mode()

0    150000
Name: salary_in_usd, dtype: int64

In [36]:
#Use describe to find a five number summary for salary
ds_df['salary_in_usd'].describe()

count       245.000000
mean      99868.012245
std       83983.326949
min        2876.000000
25%       45896.000000
50%       81000.000000
75%      130000.000000
max      600000.000000
Name: salary_in_usd, dtype: float64

In [37]:
#Find the average salary by company size
ds_df.groupby('company_size')['salary_in_usd'].mean()

company_size
L    114374.015152
M     85082.818182
S     80874.793103
Name: salary_in_usd, dtype: float64

In [38]:
#Find the average, median, and max salary by company size using .describe()
ds_df.groupby('company_size')['salary_in_usd'].describe()

,count,mean,std,min,25%,50%,75%,max
company_size,,,,,,,,
L,132.0,114374.015152,90822.326575,5898.0,56183.5,91500.0,150000.0,600000.0
M,55.0,85082.818182,72504.464408,4000.0,36337.5,71968.0,116062.5,450000.0
S,58.0,80874.793103,72038.848392,2876.0,35555.5,68364.5,101951.0,416000.0

Part 2:  Use the Diamond dataset you stored in Github

In [39]:
import pandas as pd

In [40]:
#Upload the diamond dataset in Github
# paste the url into the ''
link2 ='https://raw.githubusercontent.com/kyik1/Math-200/refs/heads/main/Diamonds.csv'

diamond_df = pd.read_csv(link2)
diamond_df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [41]:
#View the diamond_df dataset
diamond_df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [42]:
# prompt: Using dataframe diamond_df: diamond_df('clarity')[price].mean().round(2)
diamond_df.groupby('cut')['carat'].mean().round(2)

cut
Fair         1.05
Good         0.85
Ideal        0.70
Premium      0.89
Very Good    0.81
Name: carat, dtype: float64

In [43]:
#What is the average price of a diamond
diamond_df['price'].mean().round(2)

3932.8